name: bar_iland_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: any
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^4.0.5045
  eva_icons_flutter: ^2.0.0
  scoped_model: ^1.0.1
  http: ^0.12.0+4
  firebase_database: ^3.1.3
  shared_preferences: ^0.5.6+3
  rxdart: ^0.23.1
  autocomplete_textfield: ^1.7.3
  table_calendar: ^2.2.3
  intl: ^0.16.1
  searchable_dropdown: ^1.1.0
  draggable_scrollbar: ^0.0.4
  tuple: ^1.0.3
  flutter_vector_icons: ^0.2.1
  url_launcher: ^5.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: "^0.7.3"

flutter_icons:
  image_path: "assets/logo_app.jpeg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_app.jpeg
    - assets/Bar_Iland_line.png
    - assets/Bar_Iland.png
    - assets/background.jpg
    - assets/available_milk.png
    - assets/unavailable_milk.png
    - assets/Bar_Ilan_Mini_Map.jpg
    - assets/Bar_Ilan_Map.jpg
    - assets/people_party.png
    - assets/services_by_type_background.png
    #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ServicesIcons
       fonts:
         - asset: icons/ServicesIcons.ttf

  #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true